# Generated by Django 3.1.3 on 2021-02-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consistency_widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number_to_review', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gtfs_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('table', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='mode_lookup_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_id', models.ImageField(upload_to='')),
                ('mode_name', models.CharField(max_length=150)),
                ('mode_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_reason', models.TextField(null=True)),
                ('reviewed_data', models.TextField()),
                ('reviewed_data_pk_name', models.CharField(max_length=100)),
                ('reviewed_data_pk_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='results_capture_widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_score_reason', models.CharField(blank=True, choices=[(None, None), ('Optional', 'Optional'), ('Required', 'Required')], default='Optional', max_length=50, null=True)),
                ('has_score_image', models.CharField(blank=True, choices=[(None, None), ('Optional', 'Optional'), ('Required', 'Required')], default=None, max_length=50, null=True)),
                ('has_reference_link', models.CharField(blank=True, choices=[(None, None), ('Optional', 'Optional'), ('Required', 'Required')], default=None, max_length=50, null=True)),
                ('has_reference_date', models.CharField(blank=True, choices=[(None, None), ('Optional', 'Optional'), ('Required', 'Required')], default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=150)),
                ('mode', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('In progress', 'In progress'), ('In review', 'In review'), ('Completed', 'Completed')], default='In progress', max_length=50)),
                ('completed_date', models.DateTimeField(null=True)),
                ('final_score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('help_text', models.TextField()),
                ('results_capture_widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.results_capture_widget')),
            ],
        ),
        migrations.CreateModel(
            name='review_widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_field', models.BooleanField(default=True)),
                ('related_field_other_table', models.CharField(max_length=150, null=True)),
                ('related_field_same_table', models.ManyToManyField(related_name='_review_widget_related_field_same_table_+', to='gtfs_grading_app.gtfs_field')),
            ],
        ),
        migrations.CreateModel(
            name='review_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency_widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gtfs_grading_app.consistency_widget')),
                ('data_selector', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.data_selector')),
                ('gtfs_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.gtfs_field')),
                ('results_capture_widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gtfs_grading_app.results_capture_widget')),
                ('review_widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gtfs_grading_app.review_widget')),
            ],
        ),
        migrations.CreateModel(
            name='result_reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=200, null=True)),
                ('url', models.URLField()),
                ('published_reference_date', models.DateTimeField(null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs_grading_app.result')),
            ],
        ),
        migrations.CreateModel(
            name='result_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='result_images')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs_grading_app.result')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.review'),
        ),
        migrations.AddField(
            model_name='result',
            name='review_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.review_category'),
        ),
        migrations.AddField(
            model_name='result',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.score'),
        ),
        migrations.CreateModel(
            name='related_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtfs_field_value', models.TextField()),
                ('gtfs_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.gtfs_field')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs_grading_app.result')),
            ],
        ),
        migrations.CreateModel(
            name='consistency_widget_visual_example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='consistency_images/')),
                ('consistency_widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.consistency_widget')),
            ],
        ),
        migrations.CreateModel(
            name='consistency_widget_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_display_text', models.CharField(max_length=150)),
                ('consistency_widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.consistency_widget')),
            ],
        ),
    ]
