# Generated by Django 3.1.3 on 2020-11-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsistencyWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GtfsField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('table', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_reason', models.CharField(max_length=150)),
                ('reviewed_data', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsCaptureWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_field_other_table', models.CharField(max_length=150, null=True)),
                ('related_field_same_table', models.ManyToManyField(related_name='_reviewwidget_related_field_same_table_+', to='gtfs_grading_app.GtfsField')),
                ('review_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.gtfsfield')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('review_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.gtfsfield')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('score_help_text', models.CharField(max_length=150)),
                ('ReviewWidget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.reviewwidget')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency_widget', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.consistencywidget')),
                ('results_widget', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.resultscapturewidget')),
                ('review_widget', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.reviewwidget')),
                ('selected_rows', models.ManyToManyField(to='gtfs_grading_app.SelectedRows')),
            ],
        ),
        migrations.AddField(
            model_name='resultscapturewidget',
            name='review_widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.reviewwidget'),
        ),
        migrations.AddField(
            model_name='resultscapturewidget',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.score'),
        ),
        migrations.CreateModel(
            name='ResultImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.result')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='review_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.reviewcategory'),
        ),
        migrations.AddField(
            model_name='result',
            name='reviewed_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.gtfsfield'),
        ),
        migrations.AddField(
            model_name='result',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.score'),
        ),
        migrations.CreateModel(
            name='ConsistencyWidgetVisualExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('consistency_widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.consistencywidget')),
            ],
        ),
        migrations.CreateModel(
            name='ConsistencyWidgetLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_display_text', models.CharField(max_length=150)),
                ('consistency_widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.consistencywidget')),
            ],
        ),
    ]
