# Generated by Django 3.1.3 on 2020-12-02 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consistency_widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_visual_example', models.BooleanField(default=False)),
                ('has_link', models.BooleanField(default=False)),
                ('has_other_text', models.BooleanField(default=False)),
                ('other_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='gtfs_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('table', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_reason', models.CharField(max_length=150)),
                ('reviewed_data', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='results_capture_widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_score', models.BooleanField(default=True)),
                ('has_score_reason', models.BooleanField(default=True)),
                ('has_score_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='selected_rows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('gtfs_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.gtfs_field')),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('score_help_text', models.CharField(max_length=150)),
                ('results_capture_widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.results_capture_widget')),
            ],
        ),
        migrations.CreateModel(
            name='review_widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_field', models.BooleanField(default=True)),
                ('has_related_field_same_table', models.BooleanField(default=False)),
                ('has_related_field_other_table', models.BooleanField(default=False)),
                ('related_field_other_table', models.CharField(max_length=150, null=True)),
                ('related_field_same_table', models.ManyToManyField(related_name='_review_widget_related_field_same_table_+', to='gtfs_grading_app.gtfs_field')),
            ],
        ),
        migrations.CreateModel(
            name='review_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_table', models.CharField(max_length=150)),
                ('consistency_widget', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.consistency_widget')),
                ('gtfs_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.gtfs_field')),
                ('results_capture_widget', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.results_capture_widget')),
                ('review_widget', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.review_widget')),
            ],
        ),
        migrations.CreateModel(
            name='result_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.result')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='review_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.review_category'),
        ),
        migrations.AddField(
            model_name='result',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.score'),
        ),
        migrations.AddField(
            model_name='result',
            name='selected_rows',
            field=models.ManyToManyField(to='gtfs_grading_app.selected_rows'),
        ),
        migrations.CreateModel(
            name='consistency_widget_visual_example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('consistency_widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.consistency_widget')),
            ],
        ),
        migrations.CreateModel(
            name='consistency_widget_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_display_text', models.CharField(max_length=150)),
                ('consistency_widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.consistency_widget')),
            ],
        ),
    ]
