# Generated by Django 3.1.3 on 2020-12-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score_help_text',
            new_name='help_text',
        ),
    ]
