# Generated by Django 3.1.3 on 2020-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0002_auto_20201228_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number_to_review', models.IntegerField(null=True)),
            ],
        ),
    ]
