# Generated by Django 3.1.3 on 2020-12-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0003_data_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_category',
            name='data_selector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.data_selector'),
        ),
    ]
