# Generated by Django 3.1.3 on 2021-01-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0006_auto_20201230_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='related_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtfs_field_value', models.TextField()),
                ('gtfs_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.gtfs_field')),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='selected_rows',
        ),
        migrations.DeleteModel(
            name='selected_rows',
        ),
        migrations.AddField(
            model_name='related_field',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.result'),
        ),
    ]
