# Generated by Django 3.1.3 on 2021-01-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0007_auto_20210105_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2011-01-01'),
            preserve_default=False,
        ),
    ]
