# Generated by Django 3.1.3 on 2021-01-05 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0008_auto_20210105_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='reviewed_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.score'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score_reason',
            field=models.TextField(null=True),
        ),
    ]
