# Generated by Django 3.1.3 on 2021-01-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0010_auto_20210107_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='result_reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=200, null=True)),
                ('url', models.URLField()),
                ('published_reference_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtfs_grading_app.result')),
            ],
        ),
        migrations.DeleteModel(
            name='result_url',
        ),
    ]
