# Generated by Django 3.1.3 on 2021-01-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0011_auto_20210108_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results_capture_widget',
            name='has_reference_date',
            field=models.CharField(choices=[('Optional', 'Optional'), ('Required', 'Required')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_capture_widget',
            name='has_reference_link',
            field=models.CharField(choices=[('Optional', 'Optional'), ('Required', 'Required')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_capture_widget',
            name='has_score_image',
            field=models.CharField(choices=[('Optional', 'Optional'), ('Required', 'Required')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_capture_widget',
            name='has_score_reason',
            field=models.CharField(choices=[('Optional', 'Optional'), ('Required', 'Required')], default='Optional', max_length=50, null=True),
        ),
    ]
