# Generated by Django 3.1.3 on 2021-02-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0014_auto_20210204_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_reference',
            name='published_reference_date',
            field=models.DateTimeField(null=True),
        ),
    ]
