# Generated by Django 3.1.3 on 2021-02-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0019_auto_20210204_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], default='In progress', max_length=50),
        ),
    ]
