# Generated by Django 3.1.3 on 2021-02-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_grading_app', '0020_review_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='final_score',
            field=models.FloatField(null=True),
        ),
    ]
